
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
  namespace: constraints-cpu-example
spec:
  limits:
  - max:
      cpu: "800m"
    min:
      cpu: "200m"
    type: Container